const labels: Record<string, string> = {
  normal: 'Normal',
  advertencia: 'Advertencia',
  critico: 'Crítico',
  critica: 'Crítica',
  informativa: 'Informativa',
  abierta: 'Abierta',
  en_atencion: 'En atención',
  cerrada: 'Cerrada',
  activo: 'Activo',
  inactivo: 'Inactivo',
  mantenimiento: 'Mantenimiento',
  desconectado: 'Desconectado',
  active: 'Activo',
  inactive: 'Inactivo',
  queued: 'En cola',
  sent: 'Enviada',
  failed: 'Fallida',
  administrador: 'Administrador',
  regente_farmacia: 'Regente de farmacia',
  auxiliar_farmacia: 'Auxiliar de farmacia',
  calidad: 'Calidad',
  mantenimiento_biomedico: 'Mantenimiento biomédico',
  consulta_auditor: 'Consulta / Auditor',
  simulador: 'Simulador',
  manual: 'Manual',
  MQTT: 'MQTT',
  email: 'Correo electrónico',
  sms: 'SMS',
  call: 'Llamada',
  calibration: 'Calibración',
  certificate: 'Certificado',
  maintenance: 'Mantenimiento',
  other: 'Otro',
  create_sensor: 'Creación de sensor',
  update_sensor: 'Actualización de sensor',
  sensor_status: 'Cambio de estado del sensor',
  login_success: 'Inicio de sesión exitoso',
  login_failed: 'Inicio de sesión fallido',
  create_user: 'Creación de usuario',
  update_user: 'Actualización de usuario',
  generate_report: 'Generación de reporte',
  attend_alarm: 'Atención de alarma',
  close_alarm: 'Cierre de alarma',
  create_corrective_action: 'Registro de acción correctiva',
  create_notification_contact: 'Creación de contacto de notificación',
  create_device_file: 'Registro de documento del dispositivo',
  create_site: 'Creación de sede',
  update_site: 'Actualización de sede',
  users: 'Usuarios',
  sensors: 'Sensores',
  alarms: 'Alarmas',
  corrective_actions: 'Acciones correctivas',
  notification_contacts: 'Contactos de notificación',
  device_files: 'Documentos de dispositivos',
  sites: 'Sedes',
  reports: 'Reportes',
  system: 'Sistema',
  frontend: 'Interfaz'
};

export function humanize(value?: string | null) {
  if (!value) return 'Sin información';
  return labels[value] || value.replaceAll('_', ' ').replace(/^./, (letter) => letter.toUpperCase());
}
